server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8000/storage
    username: storage
    password: 1234
  jpa:
    hibernate:
      ddl-auto: "update"
      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/service-storage
    jwt:
      secret_key: 4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
      access_token_expiration: 36000000
      refresh_token_expiration: 252000000

keycloak:
  auth-server-url: http://localhost:8080
  realm: service-storage
  resource: service-storage
  public-client: true
  use-resource-role-mappings: true

logging:
  level:
    org.springframework.security: debug